### ISSUE TITLE
broken link to Block Parameters in readme

### ISSUE THREAD

**Issue by raydixon** [johnknoop/vscode-handlebars-preview#18]
### Steps to Repro

1. In your browser, open [README.md](https://github.com/johnknoop/vscode-handlebars-preview/blob/master/README.md).
2. In the [Current limitations of context generation](https://github.com/johnknoop/vscode-handlebars-preview/blob/master/README.md#current-limitations-of-context-generation) section select the link titled _Block parameters_.

#### Expected Results

You open the [Block Parameters](https://handlebarsjs.com/guide/block-helpers.html#block-parameters) documentation on the Handlebars site.

#### Actual Results

You open a 404 error page on the Handlebars site.

**Comment by johnknoop** [comment]
Thanks for finding and fixing this!
