### ISSUE TITLE
Image of data type base64 not showing in preview

### ISSUE THREAD

**Issue by David-Tennant** [johnknoop/vscode-handlebars-preview#4]
Have an image that is base 64 encoded. eg a src of `data:image/png;base64,[base64]`
![image](https://user-images.githubusercontent.com/40059359/60882958-35c62080-a249-11e9-9511-42cc5779b9d8.png)

Result: Not displayed in preview.
![image](https://user-images.githubusercontent.com/40059359/60882893-15966180-a249-11e9-82d7-9c408085a2d1.png)

Thanks for taking on this project, very helpful

**Comment by johnknoop** [comment]
Thanks for reporting this @David-Tennant .

I'll have a look at it, unless you wanna do it yourself and create a pull request?

**Comment by johnknoop** [comment]
@David-Tennant this is now fixed in beta 4 which you can find in the /vsix folder
