### ISSUE TITLE
Publishing on Open-VSX

### ISSUE THREAD

**Issue by Niklas-Dahlquist** [johnknoop/vscode-handlebars-preview#42]
Hi Johnknoop!

There is an alternative to VS Code Marketplace to download VS Code Extensions, see [Open-VSX](https://open-vsx.org/) I'd appreciate if your extension was available in that context too. Can you publish it?

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by johnknoop** [comment]
Hi Niklas

Thanks for the tip, I wasn't aware of that.

Sure, I'll try and do that!

**Comment by johnknoop** [comment]
It looks like it succeeded, but since I'm not an open-vsx user myself (never heard about if before you opened this ticket), would you mind verifying?
