### ISSUE TITLE
[feature] allow preview to execute script

### ISSUE THREAD

**Issue by wenmin92** [johnknoop/vscode-handlebars-preview#47]
It seems that the preview window does not allow execution of scripts.

The Developer tool's console says:

<img width="447" src="https://user-images.githubusercontent.com/6901815/159120178-1ee923e8-8d0a-45bb-89d3-0cad494bb461.png">

```
Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

**Comment by johnknoop** [comment]
Hi

From what I gather it should be an easy fix:

https://github.com/microsoft/vscode/issues/144006#issuecomment-1053822030

I'll try it out in the coming days and if it works I'll roll out an update.

**Comment by johnknoop** [comment]
@wenmin92 Sorry for dropping the ball on this. I've now created a reminder for myself to get this done.

**Comment by johnknoop** [comment]
Fixed and published
