### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by cbass2404** [johnknoop/vscode-handlebars-preview#48]
![Screen Shot 2022-04-06 at 11 52 50 AM](https://user-images.githubusercontent.com/68582127/162027729-db9392e5-68c5-46f6-8933-46c4f1ef81d9.png)

As you can see in the above screenshot, trying to render a .hbs file in vscode is currently giving me this error. Is this a known issue or is this a 'me issue'?

I've scoured google trying to find a work around and see if something needs to be enabled. I've had no success, so this is kind of my last hope to try to render these .hbs files for previews.

**Comment by johnknoop** [comment]
That looks a bit strange. Can you see if there's anything useful in the extension log?

**Comment by johnknoop** [comment]
https://stackoverflow.com/a/54381900

**Comment by cbass2404** [comment]
Sorry, I found the issue just after posting this I noticed none of my extensions were loading up. After restarting the computer everything seems to function as normal.
