### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by sinklair** [johnknoop/vscode-handlebars-preview#9]
Trying to use this add-in and it basically won't do anything in my VS Code. The preview function fails silently and the Generate context file command throws an error `Cannot read property 'fsPath' of undefined`

**Comment by johnknoop** [comment]
Hi @sinklair 

That sounds interesting. Haven't seen this before. What OS are you on? And could you paste a HBS file that fails?

**Comment by sinklair** [comment]
MacOS 10.14.6

I realized after your response that the preview wasn't working because I wasn't using the .hbs extension - all of my files were named .html.

However, I still can't get the content generation to work - error as above. 

Here is a sample file: https://gist.github.com/sinklair/09dc16ceafa5adf8385a68098d8c8325

**Comment by johnknoop** [comment]
@sinklair The context generation seems to work fine for me, but I'm on Windows, and I do remember something about the `fs.promises` API (which I'm using) being experimental, so it's propably not supported by your Node version.

I'll see what I can do about using the non-async version of the fs API instead, or possibly something else.

**Comment by sinklair** [comment]
@johnknoop thanks for this. 

Is there a way to have the preview work on files with extensions other than hbs?

**Comment by johnknoop** [comment]
For the preview, I actually don't look at the file extension, but rather VS Code´s "resource lang id" which you can see [here](https://github.com/johnknoop/vscode-handlebars-preview/blob/master/package.json#L46). So I'm guessing, if you click the "Select language mode" down on the status bar and select Handlebars, you should be able to get the Preview menu item.

**Comment by johnknoop** [comment]
Hmm, it doesn't seem to be as simple as setting the Handlebars language mode for any file. I'll look into it.

**Comment by johnknoop** [comment]
@sinklair May I trouble you for some details around the `Cannot read property 'fsPath' of undefined` error?

Did you right-click on a file in the sidebar or on the tab of an open editor? And in case of the latter, did the file in the editor exist on disk or was it a new file?

I'm gonna borrow a Macbook here at work and try to reproduce it.

Thanks

**Comment by sinklair** [comment]
@johnknoop just tested this and the issue appears to be when you have the file open in editor and choose `Generate context file` from the command palette. 

Right-clicking the file in sidebar and choosing this command works as expected. 

In both cases it is a saved file.

**Comment by johnknoop** [comment]
@sinklair I just published a new version to VS Code marketplace, in which the problem should be fixed.

Regarding support for file extensions other than '.hbs' and '.handlebars' I'll open a new ticket for that.

Thanks for helping out!
